# GridSearch + Validation croisée + Hyperparamètres

## 0) Imports + dataset

In [4]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split, StratifiedKFold, GridSearchCV, RandomizedSearchCV
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression

In [5]:
# Dataset réel
X, y = load_wine(return_X_y=True)

# Split train/test (test = évaluation finale)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print("Train:", X_train.shape, "Test:", X_test.shape)

Train: (142, 13) Test: (36, 13)

In [10]:
display(pd.DataFrame(X, columns=load_wine().feature_names).head(5))
display(pd.DataFrame(y, columns=["target"]).head(5))

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0

   target
0       0
1       0
2       0
3       0
4       0

## 1) Rappel : paramètres vs hyperparamètres 

- **Paramètres :** appris pendant fit (ex: poids d’un modèle linéaire).

- **Hyperparamètres :** choisis avant fit (ex: k pour KNN, C pour Logistic Regression).

## 2) Pourquoi la Cross-Validation ?

In [11]:
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

KFold mais Stratified car en classification, on garde la proportion des classes similaire dans chaque fold.

## 3) Exemple 1 — KNN : chercher le meilleur k avec GridSearchCV

### 3.1 Pipeline (scaling + modèle)

In [15]:
pipe_knn = Pipeline([
    ("scaler", StandardScaler()),
    ("model", KNeighborsClassifier())
])
display(pipe_knn)

Pipeline(steps=[('scaler', StandardScaler()),
                ('model', KNeighborsClassifier())])

### 3.2 Grille d’hyperparamètres

In [21]:
param_grid_knn = {
    "model__n_neighbors": range(1, 11)
}

### 3.3 GridSearchCV sur jeu de validation

In [22]:
# Séparation du train en train/validation pour la CV
print("Avant split:", X_train.shape)
print("Avant split:", y_train.shape)
print("----------------------------")

X_train, X_val, y_train, y_val = train_test_split(
    X_train, y_train, test_size=0.2, random_state=42, stratify=y_train
)

print("Après split:", X_train.shape)
print("Après split:", y_train.shape)
print("Validation set shape:", X_val.shape)
print("Validation set shape:", y_val.shape)

Avant split: (142, 13)
Avant split: (142,)
----------------------------
Après split: (113, 13)
Après split: (113,)
Validation set shape: (29, 13)
Validation set shape: (29,)

In [23]:
grid_knn = GridSearchCV(
    estimator=pipe_knn,
    param_grid=param_grid_knn,
    cv=cv,
    scoring="accuracy",
    n_jobs=-1,
    verbose=1
)

grid_knn.fit(X_val, y_val)

print("Meilleurs hyperparamètres:", grid_knn.best_params_)
print("Meilleur score CV:", round(grid_knn.best_score_, 4))

Fitting 5 folds for each of 10 candidates, totalling 50 fits
Meilleurs hyperparamètres: {'model__n_neighbors': 9}
Meilleur score CV: 1.0

In [24]:
# Entrainement final sur le train avec les meilleurs hyperparamètres
best_k = grid_knn.best_params_["model__n_neighbors"]
final_pipe_knn = Pipeline([
    ("scaler", StandardScaler()),
    ("model", KNeighborsClassifier(n_neighbors=best_k))
])
final_pipe_knn.fit(X_train, y_train)

Pipeline(steps=[('scaler', StandardScaler()),
                ('model', KNeighborsClassifier(n_neighbors=9))])

In [25]:
# Evaluation finale sur le test set
print("Score test final:", round(final_pipe_knn.score(X_test, y_test), 3))

Score test final: 1.0

#### Point clés :

- GridSearch essaie tous les k

- Pour chaque k, il fait une CV (5 entraînements sur les 5 folds)

- Il moyenne les scores

- Il garde le meilleur

- Puis il évalue une seule fois sur le test

## 4) Exemple 2 — Logistic Regression : chercher les meilleurs C et max_iter

### 4.1 Pipeline

In [27]:
pipe_lr = Pipeline([
    ("scaler", StandardScaler()),
    ("model", LogisticRegression())
])

### 4.2 Grille

In [28]:
param_grid_lr = {
    "model__C": [0.01, 0.1, 1, 10, 100],
    "model__max_iter": [100, 500, 1000]
}

### 4.3 GridSearch

In [29]:
grid_lr = GridSearchCV(
    estimator=pipe_lr,
    param_grid=param_grid_lr,
    cv=cv,
    scoring="accuracy",
    n_jobs=-1,
    verbose=1
)

grid_lr.fit(X_train, y_train)

print("Meilleurs hyperparamètres:", grid_lr.best_params_)
print("Meilleur score CV:", round(grid_lr.best_score_, 3))
print("Score test final:", round(grid_lr.score(X_test, y_test), 3))

Fitting 5 folds for each of 15 candidates, totalling 75 fits
Meilleurs hyperparamètres: {'model__C': 0.01, 'model__max_iter': 100}
Meilleur score CV: 0.982
Score test final: 0.972

In [30]:
## Affichage des differents scores de la cv
cv_results = grid_lr.cv_results_
for mean_score, params in zip(cv_results["mean_test_score"], cv_results["params"]):
    print(f"Score moyen: {mean_score:.3f} - Hyperparamètres: {params}")

Score moyen: 0.982 - Hyperparamètres: {'model__C': 0.01, 'model__max_iter': 100}
Score moyen: 0.982 - Hyperparamètres: {'model__C': 0.01, 'model__max_iter': 500}
Score moyen: 0.982 - Hyperparamètres: {'model__C': 0.01, 'model__max_iter': 1000}
Score moyen: 0.982 - Hyperparamètres: {'model__C': 0.1, 'model__max_iter': 100}
Score moyen: 0.982 - Hyperparamètres: {'model__C': 0.1, 'model__max_iter': 500}
Score moyen: 0.982 - Hyperparamètres: {'model__C': 0.1, 'model__max_iter': 1000}
Score moyen: 0.973 - Hyperparamètres: {'model__C': 1, 'model__max_iter': 100}
Score moyen: 0.973 - Hyperparamètres: {'model__C': 1, 'model__max_iter': 500}
Score moyen: 0.973 - Hyperparamètres: {'model__C': 1, 'model__max_iter': 1000}
Score moyen: 0.973 - Hyperparamètres: {'model__C': 10, 'model__max_iter': 100}
Score moyen: 0.973 - Hyperparamètres: {'model__C': 10, 'model__max_iter': 500}
Score moyen: 0.973 - Hyperparamètres: {'model__C': 10, 'model__max_iter': 1000}
Score moyen: 0.964 - Hyperparamètres: {'model__C': 100, 'model__max_iter': 100}
Score moyen: 0.964 - Hyperparamètres: {'model__C': 100, 'model__max_iter': 500}
Score moyen: 0.964 - Hyperparamètres: {'model__C': 100, 'model__max_iter': 1000}

### Ce que fait réellement GridSearchCV

Pour chaque combinaison d’hyperparamètres :

- Il applique la validation croisée

- Il calcule le score moyen

- Il compare les scores

- Il sélectionne le meilleur

- On réentraîne sur tout le train avec la meilleure config

**Donc :**

> GridSearchCV = exploration systématique + validation croisée automatisée.

## 5) Comparer 2 modèles proprement (même protocole)

### 5.1 Comparaison des GridSearch directement

In [31]:
grids_dict = {
    "KNN": grid_knn,
    "LogReg": grid_lr
}

In [32]:
results = {}

for name, grid in grids_dict.items():
    results[name] = {
        "best_params": grid.best_params_,
        "cv_score": grid.best_score_,
        "test_score": grid.score(X_test, y_test)
    }

results

{'KNN': {'best_params': {'model__n_neighbors': 9},
  'cv_score': np.float64(1.0),
  'test_score': 0.9722222222222222},
 'LogReg': {'best_params': {'model__C': 0.01, 'model__max_iter': 100},
  'cv_score': np.float64(0.9822134387351777),
  'test_score': 0.9722222222222222}}

### 5.2 Comparaison des modèles (pipeline et grille à comparer)

In [33]:
models = {
    # nom_du_model : (pipeline, grille)
    "KNN": (pipe_knn, param_grid_knn),
    "LogReg": (pipe_lr, param_grid_lr)
}

results = {}

for name, (pipe, grid) in models.items():
    gs = GridSearchCV(pipe, grid, cv=cv, scoring="accuracy", n_jobs=-1)
    gs.fit(X_train, y_train)

    results[name] = {
        "best_params": gs.best_params_,
        "cv_score": gs.best_score_,
        "test_score": gs.score(X_test, y_test)
    }

results

{'KNN': {'best_params': {'model__n_neighbors': 9},
  'cv_score': np.float64(0.9553359683794467),
  'test_score': 1.0},
 'LogReg': {'best_params': {'model__C': 0.01, 'model__max_iter': 100},
  'cv_score': np.float64(0.9822134387351777),
  'test_score': 0.9722222222222222}}

**Ici on observe :**

- Comparaison équitable

- Même jeu de données

- Même CV

- Même métrique

- C’est une vraie logique “entreprise”.

## Option (facultative) — RandomizedSearchCV

### Quand la grille est énorme, on échantillonne au hasard.

In [42]:
#from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import randint

rand_knn = RandomizedSearchCV(
    estimator=pipe_knn,
    param_distributions={"model__n_neighbors": randint(1, 51)},
    n_iter=20,
    cv=cv,
    scoring="accuracy",
    n_jobs=-1,
    random_state=42,
    verbose=1,
    
)

rand_knn.fit(X_train, y_train)

print("Best params (random):", rand_knn.best_params_)
print("Best CV score:", round(rand_knn.best_score_, 3))
print("Test score:", round(rand_knn.score(X_test, y_test), 3))

Fitting 5 folds for each of 20 candidates, totalling 100 fits
Best params (random): {'model__n_neighbors': 15}
Best CV score: 0.973
Test score: 1.0

In [43]:
# Affichage des differents scores de la cv et des hyperparamètres testés
cv_results = rand_knn.cv_results_
for mean_score, params in zip(cv_results["mean_test_score"], cv_results["params"]):
    print(f"Score moyen: {mean_score:.3f} - Hyperparamètres: {params}")

Score moyen: 0.947 - Hyperparamètres: {'model__n_neighbors': 39}
Score moyen: 0.955 - Hyperparamètres: {'model__n_neighbors': 29}
Score moyen: 0.973 - Hyperparamètres: {'model__n_neighbors': 15}
Score moyen: 0.956 - Hyperparamètres: {'model__n_neighbors': 43}
Score moyen: 0.946 - Hyperparamètres: {'model__n_neighbors': 8}
Score moyen: 0.964 - Hyperparamètres: {'model__n_neighbors': 21}
Score moyen: 0.947 - Hyperparamètres: {'model__n_neighbors': 39}
Score moyen: 0.964 - Hyperparamètres: {'model__n_neighbors': 19}
Score moyen: 0.964 - Hyperparamètres: {'model__n_neighbors': 23}
Score moyen: 0.964 - Hyperparamètres: {'model__n_neighbors': 11}
Score moyen: 0.964 - Hyperparamètres: {'model__n_neighbors': 11}
Score moyen: 0.964 - Hyperparamètres: {'model__n_neighbors': 24}
Score moyen: 0.947 - Hyperparamètres: {'model__n_neighbors': 36}
Score moyen: 0.956 - Hyperparamètres: {'model__n_neighbors': 40}
Score moyen: 0.964 - Hyperparamètres: {'model__n_neighbors': 24}
Score moyen: 0.946 - Hyperparamètres: {'model__n_neighbors': 3}
Score moyen: 0.955 - Hyperparamètres: {'model__n_neighbors': 22}
Score moyen: 0.946 - Hyperparamètres: {'model__n_neighbors': 2}
Score moyen: 0.964 - Hyperparamètres: {'model__n_neighbors': 24}
Score moyen: 0.947 - Hyperparamètres: {'model__n_neighbors': 44}

## Récap Global

- CV : robuste, réduit l’effet “split chanceux”

- GridSearchCV : teste toutes les combinaisons

- RandomizedSearchCV : teste un nombre limité de combinaisons aléatoires - si la grille est trop grande

- Pipeline : garantit que le preprocessing est fait correctement dans chaque fold

- Test set : une seule fois, à la fin

## Message fondamental (important pour le DL)

**En ML, le cœur du travail n’est pas le modèle. C’est la méthode de validation.**

**En Deep Learning, ce sera exactement pareil :**

- On choisira learning rate

- On choisira architecture

- On choisira nombre de couches

- On regardera la courbe validation

- La validation est déjà introduite.